oDipUI/initial_enquiry/urls.py
from django.urls import path
from .views import (
    customer_details,
    property_details,
    calculate_ltv,
    thank_you,
)

urlpatterns = [
    path('yourdetails/', customer_details, name='customer_details'),
    path('propertydetails/', property_details, name='property_details'),
    path('ajax/calculate_ltv/', calculate_ltv, name='calculate_ltv'),
    path('thankyou/', thank_you, name='thank_you'),
]

oDipUI/oDipUI/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('initial_enquiry.urls')),    
    path('admin/', admin.site.urls),
]

handler404 = 'initial_enquiry.views.error_404'
handler500 = 'initial_enquiry.views.error_500'

oDipUI/initial_enquiry/models.py
from django.db import models

# Create your models here.

oDipUI/initial_enquiry/forms.py
""" form classes for the enquiry creator """

from django.core.validators import RegexValidator
from django import forms
from django.utils import timezone
from django.conf import settings


class CustomerDetailsForm(forms.Form):
    """ Page 1 of the Initial Enquiry journey """

    # Custom Regex validation for telephone number
    phone_regex = RegexValidator(regex=r'^(((\+44\s?\d{4}|\(?0\d{4}\)?)\s?\d{3}\s?\d{3})|((\+44\s?\d{3}|\(?0\d{3}\)?)\s?\d{3}\s?\d{4})|((\+44\s?\d{2}|\(?0\d{2}\)?)\s?\d{4}\s?\d{4}))(\s?\#(\d{4}|\d{3}))?$',
        message="Provide a valid UK Phone Number.")

    first_name = forms.CharField(max_length=40, label="First Name")
    last_name = forms.CharField(max_length=40, label="Last Name")
    building = forms.CharField(max_length=50, required=False, label="Building and Street")
    street = forms.CharField(max_length=50, required=False, label="Street")
    town = forms.CharField(max_length=50, required=False, label="Town")
    county = forms.CharField(max_length=50, required=False, label="County")
    postcode = forms.CharField(max_length=10, required=False, label="Postcode")
    telephone_number = forms.CharField(validators=[phone_regex], max_length=17, label="Telephone Number", widget=forms.TextInput(attrs={'type': 'tel'}))
    email_address = forms.EmailField(max_length=254, required=False, label="Email Address", widget=forms.TextInput(attrs={'type': 'email'}))

    MORNING = 'M'
    EARLY_AFTERNOON = 'EA'
    LATE_AFTERNOON = 'LA'
    SATURDAY = 'S'
    PREFERRED_TIME_TO_CONTACT_CHOICES = [
        (MORNING, '9am - 12pm (Mon-Fri)'),
        (EARLY_AFTERNOON, '12pm - 3pm (Mon-Fri)'),
        (LATE_AFTERNOON, '3pm - 5pm (Mon-Fri)'),
        (SATURDAY, '9am - 2pm (Sat)'),
    ]
    preferred_time_to_contact = forms.ChoiceField(
        widget=forms.RadioSelect,
        choices=PREFERRED_TIME_TO_CONTACT_CHOICES,
        label="Preferred Time to Call"
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Override default "required" validation message to mention the field name
        for field in self.fields.values():
            field.error_messages = {'required' : f'{field.label} is required'}


class PropertyDetailsForm(forms.Form):
    """ Page 2 of the Initial Enquiry journey """

    ltv_value = forms.FloatField(max_value=100, min_value=0, label="LTV")
    annual_income = forms.IntegerField(label="Annual Income", widget=forms.TextInput(attrs={'type': 'number'}))    
    loan_amount = forms.IntegerField(label="Loan Amount", widget=forms.TextInput(attrs={'type': 'number'}))
    property_value = forms.IntegerField(label="Property Value", widget=forms.TextInput(attrs={'type': 'number'}))

    NEW_HOUSE = 'NH'
    REMORTGAGE = 'RM'
    MORTGAGE_TYPE_CHOICES = [
        (NEW_HOUSE, 'New House'),
        (REMORTGAGE, 'Remortgage'),
    ]
    mortgage_type = forms.ChoiceField(
        widget=forms.RadioSelect,
        choices=MORTGAGE_TYPE_CHOICES,
        label="Mortgage Type"
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Override default "required" validation message to mention the field name
        for field in self.fields.values():
            field.error_messages = {'required' : f'{field.label} is required'}

    def clean_ltv_value(self):
        """ Validates LTV against MAX_LTV """
        max_ltv = 80
        ltv = self.cleaned_data['ltv_value']

        if ltv > max_ltv:
            raise forms.ValidationError("LTV is too high, consider reducing your Loan Amount")
        return ltv


class EnquiryForm(forms.Form):
    """ Final full enquiry model """

    # class Meta:
    #     model = Enquiry
    #     fields = ['first_name', 'last_name', 'building', 'street', 'town', 'county', 'postcode', 'telephone_number', 'email', 'preferred_time_to_contact',
    #               'annual_income', 'loan_amount', 'property_value', 'mortgage_type' ]

    date_created = forms.DateField(initial=timezone.now, label="Date Created")
    has_been_contacted = forms.BooleanField(initial=False, label="Has been Contacted?")

oDipUI/initial_enquiry/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, UpdateView
from django.conf import settings
from django.http import JsonResponse
from .forms import CustomerDetailsForm, PropertyDetailsForm, EnquiryForm
from .helpers.providers import EnquiryProvider
from requests import post
import json

ODIP_API_ENDPOINT = "http://ec2-35-178-182-161.eu-west-2.compute.amazonaws.com/send-enquiry"
LTVCALCULATOR_API_ENDPOINT = "https://eposdjjkpd.execute-api.eu-west-2.amazonaws.com/dev/ltv-calculator-v1"

def customer_details(request):
    """ Customer Details form, first page of Enquiry """

    # Set initial response code for testing purposes
    response_code = 200

    if request.method == "POST":
        form = CustomerDetailsForm(request.POST, use_required_attribute=False)

        if form.is_valid():
            # Save to the session to be retreived later
            request.session["customer_details"] = form.cleaned_data
            return redirect("property_details")
        response_code = 400
    else:
        form = CustomerDetailsForm(use_required_attribute=False)

    context = {
        "form": form
    }
    return render(request, "customer_details.html", context, status=response_code)


def property_details(request):
    """ Property Details form, second page of Enquiry """

    # Set initial response code for testing purposes
    response_code = 400

    # Session check to verify journey integrity
    if not "customer_details" in request.session:
        return redirect("customer_details")

    if request.method =="POST":
        form = PropertyDetailsForm(request.POST, use_required_attribute=False)
        if form.is_valid():
            property_details_data = form.cleaned_data
            customer_details_data = request.session["customer_details"]

            # Consolidate data from other pages to prep for db entry
            enquiry_data = EnquiryProvider()
            enquiry_data.add(property_details_data)
            enquiry_data.add(customer_details_data)

            # Convert all values to string before sending to API
            string_data = enquiry_data.get_list_with_string_values()

            # Post the data to the API
            response = post(ODIP_API_ENDPOINT, json = string_data)

            print(response.text)

            return redirect("thank_you")

    else:
        # Generate a new form page and set response code
        form = PropertyDetailsForm(use_required_attribute=False)
        response_code = 200

    context = {
        "form": form
    }
    return render(request, "property_details.html", context, status=response_code)


def calculate_ltv(request):

    loan_amount = int(request.GET.get('loanamount', None))
    property_value = int(request.GET.get('propertyvalue', None))

    property_data = {
        "loan_amount": loan_amount,
        "property_value": property_value
    }

    # Send data to the LTV Calculator API
    response = post(LTVCALCULATOR_API_ENDPOINT, json = property_data)

    # Map the response data to usable values
    ltv_data = response.json()
    ltv_value = ltv_data['body']['ltv_percentage']
    ltv_acceptable = ltv_data['body']['is_acceptable']

    # Check if the value is within specified acceptance criteria
    if ltv_acceptable:
        ltv_css = "ltv_acceptable"
        visibility_css = "hidden"
    else:
        ltv_css = "ltv_unacceptable"
        visibility_css = "visible"

    data = {
        'ltv': ltv_value,
        'ltv_css': ltv_css,
        'visibility_css': visibility_css,
    }
    return JsonResponse(data)

def thank_you(request):
    """ Page displayed on submission complete """

    # Session check to verify journey integrity
    if not "customer_details" in request.session:
        return redirect("customer_details")

    # Clean the session
    del request.session["customer_details"]

    return render(request, "thank_you.html")


def error_404(request, exception):
    """ Custom 404 error handler """
    return render(request, 'error/404.html', status=404)

def error_500(request):
    """ Custom 500 error handler """
    return render(request, 'error/500.html', status=500)

oDipUI/initial_enquiry/templates/_layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{% block title %}{% endblock %} - Online DIP</title>
    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link rel="stylesheet" href="{% static 'css/style-dark.css' %}" />

</head>
<body>
    <div class="skip-to-content">
        <a href="#main-content">Skip to main content</a>
    </div>
    <header>
        <div class="container">
            <span class="logo-box"></span>
        </div>
    </header>

    <div class="content" id="main-content">
        {% block content %}

        {% endblock %}
    </div>
    

    <footer>
        <div class="container">
            <ul>
                <li><a href="https://www.newcastle.co.uk/faqs/legal-information/" target="_blank">Legal information</a></li>
                <li><a href="https://www.newcastle.co.uk/faqs/website-online-services/privacy-data-protection-policy/" target="_blank">Privacy & Cookies</a></li>
                <li><a href="https://online.newcastle.co.uk/OFIS/MoreInfo.aspx?MoreInfoRef=AccountSecurity" target="_blank">Security Information</a></li>
                <li><a href="http://www.newcastle.co.uk/contact" target="_blank">Contact Us</a></li>
                <li><a href="https://www.newcastle.co.uk/complaints/" target="_blank">Complaints</a></li>
                <li><a href="https://online.newcastle.co.uk/OFIS/MoreInfo.aspx?MoreInfoRef=Help">Help</a></li>
            </ul>
            <p>&copy; Newcastle Building Society. All Rights Reserved.</p>
            <p><address>Principal Office, Portland House, New Bridge Street, Newcastle upon Tyne, NE1 8AL.</address></p>
            <p>Newcastle Building Society is authorised by the Prudential Regulation Authority and regulated by the Financial Conduct Authority and the Prudential Regulation Authority.</p>
            <p>Newcastle Building Society is registered on the Financial Services Register under the firm reference number 156058.</p>
        </div>
    </footer>
    <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
    {% block javascript %}{% endblock %}
    </body>
</html>

oDipUI/initial_enquiry/templates/customer_details.html
{% extends "_layout.html" %}
{% block title %}Your Details{% endblock %}
{% block content %}

<div class="container">
    <h1>Your Details</h1>
    <form action="{% url 'customer_details' %}" name="odip-form" method="POST">
        {% csrf_token %}

        {% if form.errors %}
        <div class="error-summary" tabindex="-1">
            <h2>There's been a problem</h2>
            <ul>            
            {% for key, value in form.errors.items %}
                <li>{{ value }}</li>
            {% endfor %}
            </ul>
        </div>
        {% endif %}

        <div class="field">
            <label class="field-label">{{ form.first_name.label }}</label>            
            {{ form.first_name }}
        </div> 

        <div class="field">
            <label class="field-label">{{ form.last_name.label }}</label>
            {{ form.last_name }}
        </div>

        <h3>What is your Address?</h3>

        <div class="field">
            <label class="field-label">{{ form.building.label }}</label>
            {{ form.building }}
        </div>
        <div class="field">
            {{ form.street }}
        </div>
        <div class="field">
            <label class="field-label">{{ form.town.label }}</label>
            {{ form.town }}
        </div>
        <div class="field">
            <label class="field-label">{{ form.county.label }}</label>
            {{ form.county }}
        </div>
        <div class="field">
            <label class="field-label">{{ form.postcode.label }}</label>
            {{ form.postcode }}
        </div>
        <div class="field">
            <label class="field-label">{{ form.telephone_number.label }}</label>
            {{ form.telephone_number }}
        </div>
        <div class="field">
            <label class="field-label">{{ form.email_address.label }}</label>
            <div class="field-hint">The data collected here will only be used to fulfill this request.</div>
            {{ form.email_address }}
        </div>

        <fieldset>
            <Legend>
                <label class="field-label">{{ form.preferred_time_to_contact.label }}</label>
            </Legend>
            <div class="field-radio-button">
                <input type="radio" name="preferred_time_to_contact" id="time-to-call-early-morning" value="M">
                <label for="time-to-call-early-morning">9am - 12pm (Mon-Fri)</label>
            </div>
            <div class="field-radio-button">
                <input type="radio" name="preferred_time_to_contact" id="time-to-call-early-afternoon" value="EA">
                <label for="time-to-call-early-afternoon">12pm - 3pm (Mon-Fri)</label>
            </div>
            <div class="field-radio-button">
                <input type="radio" name="preferred_time_to_contact" id="time-to-call-late-afternoon" value="LA">
                <label for="time-to-call-late-afternoon">3pm - 5pm (Mon-Fri)</label>
            </div>
            <div class="field-radio-button">
                <input type="radio" name="preferred_time_to_contact" id="time-to-call-saturday" value="S">
                <label for="time-to-call-saturday">9am - 2pm (Sat)</label>
            </div>
        </fieldset>

        <div class="field">
            <button type="submit" id="next">Next</button>
        </div>
    </form>
</div>

{% endblock %}

oDipUI/initial_enquiry/templates/property_details.html
{% extends "_layout.html" %}
{% block title %}Property Details{% endblock %}
{% block content %}

<div class="container">
    <h1>Property Details</h1>
    <form action="{% url 'property_details' %}" method="POST">
        {% csrf_token %}

        {% if form.errors %}
        <div class="error-summary" tabindex="-1">
            <h2>There's been a problem</h2>
            <ul>            
            {% for key, value in form.errors.items %}
                <li>{{ value }}</li>
            {% endfor %}
            </ul>
        </div>
        {% endif %}

        <div class="field">
            <label class="field-label">Annual Income</label>            
            <div class="field-prefix-group">
                <div>£</div>
                {{ form.annual_income }}
            </div>            
        </div>

        <div class="field">
            <label class="field-label">Loan Amount</label>
            <div class="field-prefix-group">
                <div>£</div>
                <input type="number" name="loan_amount" id="id_loan_amount" onchange="calculateLtv()" value="{{ form.loan_amount.value }}">
            </div>
        </div>
        
        <div class="field">
            <label class="field-label">Property Value</label>
            <div class="field-prefix-group">
                <div>£</div>
                <input type="number" name="property_value" id="id_property_value" onchange="calculateLtv()" value="{{ form.property_value.value }}">
            </div>
        </div>

        <div id="ltv">            
            <div class="field">                
                <label class="field-label">Loan to Value (LTV)</label>
                <div class="field-suffix-group">
                    <span class="field-ltv"><input type="number" name="ltv_value" min="0" max="100" step="any" id="id_ltv_value" readonly></span>
                    <div>%</div>
                </div>
                <div id="ltv-toggle1" class="hidden">
                    <p>Unfortunately we are unable to issue a mortgage with your requirements. Please lower the loan amount or call us on 0345 606 4488 to discuss your needs.</p>
                </div>
            </div>
            <div class="ltv-desc">                
                <p>An LTV is the amount of your mortgage as a percentage of the current market value of your property.</p>
                <p>The more equity (or bigger deposit) you have in your home, the lower this percentage will be and, typically, you'll be eligible for better deals.</p>
            </div>
        </div>

        <fieldset>
            <Legend>
                <label class="field-label">Mortgage Type</label>
            </Legend>
            <!-- <span class="field-error"></span> -->
            <div class="field-radio-button">
                <input type="radio" name="mortgage_type" id="mortgage-type-new-house" value="NH">
                <label for="mortgage-type-new-house">New House</label>
            </div>
            <div class="field-radio-button">
                <input type="radio" name="mortgage_type" id="mortgage-type-remortgage" value="RM">
                <label for="mortgage-type-remortgage">Remortgage</label>
            </div>            
        </fieldset>

        <div class="field">
            <button type="submit" id="submit">Submit</button>
        </div>
    </form>
</div>

{% endblock %}

{% block javascript %}
<script>
    $('#id_loan_amount').change(calculateLtv());
    $('#id_property_value').change(calculateLtv());

    function calculateLtv() {
        var loanamount = $(("#id_loan_amount")).val();
        var propertyvalue = $(("#id_property_value")).val();
        
        loanamount = loanamount || 0
        propertyvalue = propertyvalue || 0
        
        $.ajax({
            url: '/ajax/calculate_ltv/',
            data: {
                'loanamount': loanamount,
                'propertyvalue': propertyvalue
            },
            dataType: 'json',
            success: function (data) {
                document.getElementById("id_ltv_value").value = data.ltv;
                document.getElementById("id_ltv_value").className = data.ltv_css;                
                document.getElementById("ltv-toggle1").className = data.visibility_css;
            }
        });        
    };
</script>
{% endblock %}

oDipUI/initial_enquiry/templates/thank_you.html
{% extends "_layout.html" %}
{% block title %}Thank You{% endblock %}
{% block content %}

<div class="container">
    <h1>We have received your request to switch</h1>
    <p>You will be contacted by one of our advisers in the next few days.</p>
    <p>Thank you for contacting Newcastle Building Society!</p>
</div>

{% endblock %}