oDipUI/initial_enquiry/urls.py
from django.urls import path
from .views import (
    customer_details,
    property_details,
    calculate_ltv,
    thank_you,
)

urlpatterns = [
    path('yourdetails/', customer_details, name='customer_details'),
    path('propertydetails/', property_details, name='property_details'),
    path('ajax/calculate_ltv/', calculate_ltv, name='calculate_ltv'),
    path('thankyou/', thank_you, name='thank_you'),
]

oDipUI/oDipUI/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('initial_enquiry.urls')),    
    path('admin/', admin.site.urls),
]

handler404 = 'initial_enquiry.views.error_404'
handler500 = 'initial_enquiry.views.error_500'

oDipUI/initial_enquiry/models.py
from django.db import models

# Create your models here.

oDipUI/initial_enquiry/forms.py
""" form classes for the enquiry creator """

from django.core.validators import RegexValidator
from django import forms
from django.utils import timezone
from django.conf import settings


class CustomerDetailsForm(forms.Form):
    """ Page 1 of the Initial Enquiry journey """

    # Custom Regex validation for telephone number
    phone_regex = RegexValidator(regex=r'^(((\+44\s?\d{4}|\(?0\d{4}\)?)\s?\d{3}\s?\d{3})|((\+44\s?\d{3}|\(?0\d{3}\)?)\s?\d{3}\s?\d{4})|((\+44\s?\d{2}|\(?0\d{2}\)?)\s?\d{4}\s?\d{4}))(\s?\#(\d{4}|\d{3}))?$',
        message="Provide a valid UK Phone Number.")

    first_name = forms.CharField(max_length=40, label="First Name")
    last_name = forms.CharField(max_length=40, label="Last Name")
    building = forms.CharField(max_length=50, required=False, label="Building and Street")
    street = forms.CharField(max_length=50, required=False, label="Street")
    town = forms.CharField(max_length=50, required=False, label="Town")
    county = forms.CharField(max_length=50, required=False, label="County")
    postcode = forms.CharField(max_length=10, required=False, label="Postcode")
    telephone_number = forms.CharField(validators=[phone_regex], max_length=17, label="Telephone Number", widget=forms.TextInput(attrs={'type': 'tel'}))
    email_address = forms.EmailField(max_length=254, required=False, label="Email Address", widget=forms.TextInput(attrs={'type': 'email'}))

    MORNING = 'M'
    EARLY_AFTERNOON = 'EA'
    LATE_AFTERNOON = 'LA'
    SATURDAY = 'S'
    PREFERRED_TIME_TO_CONTACT_CHOICES = [
        (MORNING, '9am - 12pm (Mon-Fri)'),
        (EARLY_AFTERNOON, '12pm - 3pm (Mon-Fri)'),
        (LATE_AFTERNOON, '3pm - 5pm (Mon-Fri)'),
        (SATURDAY, '9am - 2pm (Sat)'),
    ]
    preferred_time_to_contact = forms.ChoiceField(
        widget=forms.RadioSelect,
        choices=PREFERRED_TIME_TO_CONTACT_CHOICES,
        label="Preferred Time to Call"
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Override default "required" validation message to mention the field name
        for field in self.fields.values():
            field.error_messages = {'required' : f'{field.label} is required'}


class PropertyDetailsForm(forms.Form):
    """ Page 2 of the Initial Enquiry journey """

    ltv_value = forms.FloatField(max_value=100, min_value=0, label="LTV")
    annual_income = forms.IntegerField(label="Annual Income", widget=forms.TextInput(attrs={'type': 'number'}))    
    loan_amount = forms.IntegerField(label="Loan Amount", widget=forms.TextInput(attrs={'type': 'number'}))
    property_value = forms.IntegerField(label="Property Value", widget=forms.TextInput(attrs={'type': 'number'}))

    NEW_HOUSE = 'NH'
    REMORTGAGE = 'RM'
    MORTGAGE_TYPE_CHOICES = [
        (NEW_HOUSE, 'New House'),
        (REMORTGAGE, 'Remortgage'),
    ]
    mortgage_type = forms.ChoiceField(
        widget=forms.RadioSelect,
        choices=MORTGAGE_TYPE_CHOICES,
        label="Mortgage Type"
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Override default "required" validation message to mention the field name
        for field in self.fields.values():
            field.error_messages = {'required' : f'{field.label} is required'}

    def clean_ltv_value(self):
        """ Validates LTV against MAX_LTV """
        max_ltv = 80
        ltv = self.cleaned_data['ltv_value']

        if ltv > max_ltv:
            raise forms.ValidationError("LTV is too high, consider reducing your Loan Amount")
        return ltv


class EnquiryForm(forms.Form):
    """ Final full enquiry model """

    # class Meta:
    #     model = Enquiry
    #     fields = ['first_name', 'last_name', 'building', 'street', 'town', 'county', 'postcode', 'telephone_number', 'email', 'preferred_time_to_contact',
    #               'annual_income', 'loan_amount', 'property_value', 'mortgage_type' ]

    date_created = forms.DateField(initial=timezone.now, label="Date Created")
    has_been_contacted = forms.BooleanField(initial=False, label="Has been Contacted?")

oDipUI/initial_enquiry/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, UpdateView
from django.conf import settings
from django.http import JsonResponse
from .forms import CustomerDetailsForm, PropertyDetailsForm, EnquiryForm
from .helpers.providers import EnquiryProvider
from requests import post
import json

ODIP_API_ENDPOINT = "http://ec2-35-178-182-161.eu-west-2.compute.amazonaws.com/send-enquiry"
LTVCALCULATOR_API_ENDPOINT = "https://eposdjjkpd.execute-api.eu-west-2.amazonaws.com/dev/ltv-calculator-v1"

def customer_details(request):
    """ Customer Details form, first page of Enquiry """

    # Set initial response code for testing purposes
    response_code = 200

    if request.method == "POST":
        form = CustomerDetailsForm(request.POST, use_required_attribute=False)

        if form.is_valid():
            # Save to the session to be retreived later
            request.session["customer_details"] = form.cleaned_data
            return redirect("property_details")
        response_code = 400
    else:
        form = CustomerDetailsForm(use_required_attribute=False)

    context = {
        "form": form
    }
    return render(request, "customer_details.html", context, status=response_code)


def property_details(request):
    """ Property Details form, second page of Enquiry """

    # Set initial response code for testing purposes
    response_code = 400

    # Session check to verify journey integrity
    if not "customer_details" in request.session:
        return redirect("customer_details")

    if request.method =="POST":
        form = PropertyDetailsForm(request.POST, use_required_attribute=False)
        if form.is_valid():
            property_details_data = form.cleaned_data
            customer_details_data = request.session["customer_details"]

            # Consolidate data from other pages to prep for db entry
            enquiry_data = EnquiryProvider()
            enquiry_data.add(property_details_data)
            enquiry_data.add(customer_details_data)

            # Convert all values to string before sending to API
            string_data = enquiry_data.get_list_with_string_values()

            # Post the data to the API
            response = post(ODIP_API_ENDPOINT, json = string_data)

            print(response.text)

            return redirect("thank_you")

    else:
        # Generate a new form page and set response code
        form = PropertyDetailsForm(use_required_attribute=False)
        response_code = 200

    context = {
        "form": form
    }
    return render(request, "property_details.html", context, status=response_code)


def calculate_ltv(request):

    loan_amount = int(request.GET.get('loanamount', None))
    property_value = int(request.GET.get('propertyvalue', None))

    property_data = {
        "loan_amount": loan_amount,
        "property_value": property_value
    }

    # Send data to the LTV Calculator API
    response = post(LTVCALCULATOR_API_ENDPOINT, json = property_data)

    # Map the response data to usable values
    ltv_data = response.json()
    ltv_value = ltv_data['body']['ltv_percentage']
    ltv_acceptable = ltv_data['body']['is_acceptable']

    # Check if the value is within specified acceptance criteria
    if ltv_acceptable:
        ltv_css = "ltv_acceptable"
        visibility_css = "hidden"
    else:
        ltv_css = "ltv_unacceptable"
        visibility_css = "visible"

    data = {
        'ltv': ltv_value,
        'ltv_css': ltv_css,
        'visibility_css': visibility_css,
    }
    return JsonResponse(data)

def thank_you(request):
    """ Page displayed on submission complete """

    # Session check to verify journey integrity
    if not "customer_details" in request.session:
        return redirect("customer_details")

    # Clean the session
    del request.session["customer_details"]

    return render(request, "thank_you.html")


def error_404(request, exception):
    """ Custom 404 error handler """
    return render(request, 'error/404.html', status=404)

def error_500(request):
    """ Custom 500 error handler """
    return render(request, 'error/500.html', status=500)

oDipUI/initial_enquiry/templates/adviser/enquiry_form.html
{% extends "_layout.html" %}
{% load humanize %}
{% block title %}Enquiry Details{% endblock %}
{% block content %}

<div class="container">
    <h1>Enquiry Details</h1>
    <hr>
    <form name="odip-form" method="POST">
        {% csrf_token %}

        <div class="update-flex-container">
            <div class="flex-item">
                <h4>Customer Name</h4>
                <div>{{ object.first_name }} {{ object.last_name }}</div>

                <h4>Address</h4>                
                <div>{{ object.building }}</div>
                <div>{{ object.street }}</div>
                <div>{{ object.town }}</div>
                <div>{{ object.county }}</div>
                <div>{{ object.postcode }}</div>

                <h4>Telephone Number</h4>
                <div>{{ object.telephone_number }}</div>

                <h4>Email Address</h4>
                <div>{{ object.email }}</div>
            </div> 

            <div class="flex-item">
                <h4>Annual Income</h4>
                <div>£{{ object.annual_income|intcomma }}</div>
                <h4>Requested Loan Amount</h4>
                <div>£{{ object.loan_amount|intcomma }}</div>
                <h4>Property Value</h4>
                <div>£{{ object.property_value|intcomma }}</div>                
            </div>

            <div class="flex-item">
                <h4>Extra Information</h4>
                <div>                
                    {{ object.first_name }} is looking for a 
                    {% if object.mortgage_type == 'NH' %}
                        <span style="font-weight: bolder;">New House</span>.
                    {% elif object.mortgage_type == 'RM' %}
                        <span style="font-weight: bolder;">Remortgage</span> on their existing property.
                    {% endif %}
                    The enquiry was created on <span style="font-weight: bolder;">{{ object.date_created }}</span> and they would prefer to be contacted
                    {% if object.preferred_time_to_contact == 'M' %}
                        <span style="font-weight: bolder;">in the morning</span>.
                    {% elif object.preferred_time_to_contact == 'EA' %}
                        <span style="font-weight: bolder;">early afternoon</span>.
                    {% elif object.preferred_time_to_contact == 'LA' %}
                        <span style="font-weight: bolder;">late afternoon</span>.
                    {% elif object.preferred_time_to_contact == 'S' %}
                        on <span style="font-weight: bolder;">Saturday</span>.
                    {% endif %}
                </div>
            </div>
        </div>

        <hr>
       
        <div class="field-check-box">
            <fieldset>
                {{ form.has_been_contacted }}
                <label for="id_has_been_contacted">Customer Contacted?</label>
            </fieldset>
            <div class="field-hint">Check this box once you have contacted the customer and click below to submit the form.</div>
        </div>

        <div class="enquiry-buttons">
            <button type="submit" id="submit">Submit</button>
            <a href="{% url 'adviser-list' %}" class="button button-secondary">Cancel</a>
        </div>
    </form>

    <hr>

    {% if user.is_authenticated %}        
        <div class="logout-align">
            <a class="button button-danger" href="{% url 'logout' %}">Log Out</a>
        </div>        
    {% endif %}
</div>


{% endblock %}

oDipUI/initial_enquiry/templates/adviser/enquiry_list.html
{% extends "_layout.html" %}
{% block title %}Enquiry List{% endblock %}
{% block content %}

<div class="adviser-container">
    <h1>Active Enquiries</h1>
    <hr>
    
    {% if customers %}
    <ul class="enquiry-table">
        <li class="table-header">
            <div class="col col-1">Customer Name</div>
            <div class="col col-2">Telephone Number</div>
            <div class="col col-3">Date of Enquiry</div>
            <div class="col col-4"></div>
        </li>
        {% for customer in customers %}
        <a href="{% url 'adviser-update' customer.personaldetails_ptr_id %}" tabindex="-1">
            <li class="table-row">
                <div class="col col-1 col-data" data-label="Customer Name">{{ customer.first_name }} {{ customer.last_name }}</div>
                <div class="col col-2 col-data" data-label="Telephone Number">{{ customer.telephone_number }}</div>
                <div class="col col-3 col-data" data-label="Date of Enquiry">{{ customer.date_created }}</div>
                <div class="col col-4" data-label=""><button id="{{ customer.pk }}" class="button button-small">View Enquiry</button></div>
            </li>
        </a>
        {% endfor %}
    </ul>
    {% else %}
    <p>There are no new enquiries.</p>
    {% endif %}

    <hr>

    {% if user.is_authenticated %}        
        <div class="logout-align">
            <a class="button button-danger" href="{% url 'logout' %}">Log Out</a>
        </div>        
    {% endif %}
</div>
  
{% endblock %}

oDipUI/initial_enquiry/templates/adviser/login.html
{% extends "_layout.html" %}
{% block title %}Login{% endblock %}
{% block content %}

<div class="container">
    <h1>Adviser Login</h1>
    <form name="odip-form" method="POST">
        {% csrf_token %}

        {% if form.errors %}
        <div class="error-summary" tabindex="-1">
            <h2>There's been a problem</h2>
            <ul>            
            {% for key, value in form.errors.items %}
                <li>{{ value }}</li>
            {% endfor %}
            </ul>
        </div>
        {% endif %}

        <div class="field">
            <label class="field-label">{{ form.username.label }}</label>            
            {{ form.username }}
        </div> 

        <div class="field">
            <label class="field-label">{{ form.password.label }}</label>
            <span class="field-error field-validation-valid"></span>
            {{ form.password }}            
        </div>

        <div class="field">
            <button type="submit" id="submit">Login</button>
        </div>
    </form>
</div>

{% endblock %}

oDipUI/initial_enquiry/templates/adviser/logout.html
{% extends "_layout.html" %}
{% block title %}Logout{% endblock %}
{% block content %}

<div class="container">
    <h1>You have been logged out</h1>
    <hr>
    <div>
        <a class="button" href="{% url 'login' %}">Log in</a>
    </div>
</div>

{% endblock %}